export const RESPONSE_STATUS_OK = 'OK';
export const RESPONSE_STATUS_ERROR = 'ERROR';


export const IMAGE_REG_FORM_STATE_ERROR = -1;
export const IMAGE_REG_FORM_STATE_DEFAULT = 0;
export const IMAGE_REG_FORM_STATE_PREL_FEE_RECEIVED = 1;
export const IMAGE_REG_FORM_STATE_REQUESTING_NETWORK = 2;
export const IMAGE_REG_FORM_STATE_WORKER_FEE_RECEIVED = 3;
export const IMAGE_REG_FORM_STATE_SEND_REGTICKET_MN_2_3 = 4;
export const IMAGE_REG_FORM_STATE_MN_2_3_RESPONSE_RECEIVED = 5;

export const CNODE_STATUS_CONNECTED = 0;
export const CNODE_STATUS_PENDING = 1;
export const CNODE_STATUS_DISCONNECTED = 2;

export const PYNODE_STATUS_CONNECTED = 0;
export const PYNODE_STATUS_PENDING = 1;
export const PYNODE_STATUS_DISCONNECTED = 2;

export const DATA_TYPE_USER_INFO = 0;
export const DATA_TYPE_USER_PICTURE = 1;
