export const RESPONSE_STATUS_OK = 'OK';
export const RESPONSE_STATUS_ERROR = 'ERROR';


export const IMAGE_REG_FORM_STATE_ERROR = -1;
export const IMAGE_REG_FORM_STATE_DEFAULT = 0;
export const IMAGE_REG_FORM_STATE_PREL_FEE_RECEIVED = 1;
export const IMAGE_REG_FORM_STATE_REQUESTING_NETWORK = 2;
export const IMAGE_REG_FORM_STATE_WORKER_FEE_RECEIVED = 3;
