export const RESET_STORE = 'RESET_STORE';
export const SET_IMAGE_REGISTER_FORM_ERROR = 'SET_IMAGE_REGISTER_FORM_ERROR';
export const RESET_IMAGE_REGISTER_FORM_ERRORS = 'RESET_IMAGE_REGISTER_FORM_ERRORS';
export const SET_IMAGE_REGISTER_FORM_FEE = 'SET_IMAGE_REGISTER_FORM_FEE';
export const SET_BLOCKCHAIN_ADDRESS = 'SET_BLOCKCHAIN_ADDRESS';
export const SET_BLOCKCHAIN_INFO = 'SET_BLOCKCHAIN_INFO';
export const SET_MASTERNODE_QUANTITY = 'SET_MASTERNODE_QUANTITY';
export const SET_ARTWORK_QUANTITY = 'SET_ARTWORK_QUANTITY';

export const SET_BALANCE = 'SET_BALANCE';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_IMAGE_REGISTER_WORKER_FEE = 'SET_IMAGE_REGISTER_WORKER_FEE';
export const SET_IMAGE_REGISTER_FORM_STATE = 'SET_IMAGE_REGISTER_FORM_STATE';
export const SET_IMAGE_REGTICKET_ID = 'SET_IMAGE_REGTICKET_ID';
export const SET_CNODE_STATUS = 'SET_CNODE_STATUS';
export const SET_PYNODE_STATUS = 'SET_PYNODE_STATUS';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_PASTEL_ID_LIST = 'SET_PASTEL_ID_LIST';
export const SET_PASTEL_ID_ERROR = 'SET_PASTEL_ID_ERROR';
export const SET_CURRENT_PASTEL_ID = 'SET_CURRENT_PASTEL_ID';
export const SET_CURRENT_PASSPHRASE = 'SET_CURRENT_PASSPHRASE';
export const SET_IMAGE_REGISTER_FORM_TXID = 'SET_IMAGE_REGISTER_FORM_TXID';
export const SET_IMAGE_REGISTER_FORM_TXID_ACT_TICKET = 'SET_IMAGE_REGISTER_FORM_TXID_ACT_TICKET';
export const SET_IMAGE_REGISTER_MESSAGE = 'SET_IMAGE_REGISTER_MESSAGE';
export const SET_ARTWORKS_DATA = 'SET_ARTWORKS_DATA';
export const SET_ARTWORKS_DATA_LOADING = 'SET_ARTWORKS_DATA_LOADING';

export const SET_PSL_SEND_ERROR = 'SET_PSL_SEND_ERROR';
